name: Build Aurora Corne
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Diese Action bereitet alles (SDK, West, Toolchain) automatisch vor
      - name: Install ZMK Toolchain
        uses: zmkfirmware/zmk-build-action@v2
        with:
          repository: zmkfirmware/zmk
          branch: main
          # Wir nutzen deine Config aus dem Unterordner 'config'
          config_path: config
          # Hier definieren wir die Builds
          # Die nice_nano Revision 2.0.0 wird automatisch erkannt
          board: nice_nano
          shield: splitkb_aurora_corne_left nice_view_adapter nice_view
          
      - name: Rename Left
        run: cp build/zephyr/zmk.uf2 aurora_left.uf2

      # Zweiter Durchgang für die rechte Seite
      - name: Build Right
        uses: zmkfirmware/zmk-build-action@v2
        with:
          repository: zmkfirmware/zmk
          branch: main
          config_path: config
          board: nice_nano
          shield: splitkb_aurora_corne_right

      - name: Rename Right
        run: cp build/zephyr/zmk.uf2 aurora_right.uf2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Aurora_Corne_Firmware
          path: |
            aurora_left.uf2
            aurora_right.uf2
